### PR TITLE
Libirc

### PR DESCRIPTION
**Pull request by benapetr**
This removes the hardcoded IRC code and replaces it with libirc so that the IRC connections are handled in much more efficient way.

This update resolves 2 bugs:
* Huggle no longer hang on connections (slow startup)
* You can connect to same network multiple times

### CODE REVIEW

**Comment by benapetr** [comment]
pls review @addshore @methecooldude and whoever knows some C++ I would like to push this into next release.

**Comment by benapetr** [comment]
The only problem I see here is distribution of library that is included here, some people might download the source code using zip file instead of git and this zip file doesn't contain submodules so it wouldn't compile, but I don't know if there is any way to solve it

**Comment by Hello71** [comment]
why not use libcommuni?

**Comment by benapetr** [comment]
does it even have qt integration? and what makes you feel libirc is not maintained? :P

**Comment by Hello71** [comment]
> does it even have qt integration?

the part in the repo description where it says "A cross-platform IRC framework written with Qt" looks pretty convincing to me

> and what makes you feel libirc is not maintained?

no proper README, no LICENSE, last commit was "this doesn't work in win32" on 2015-12-29.

**Pull request merged**
