### PR TITLE
Add VSCode project files

### PR DESCRIPTION
**Pull request by addshore**
It doesn't look like there are any other IDE specific files
in this repo right now, but it might be nice to include these.

### CODE REVIEW

**Comment by benapetr** [comment]
vscode project files are supposed to be generated using CMake generator for visual studio :)

**Comment by addshore** [comment]
> vscode project files are supposed to be generated using CMake generator for visual studio :)

We should add that to the docs ;)

**Comment by benapetr** [comment]
now I see this isn't for visual studio but for vscode... might merge it then but I don't know if it really works? that ./configure script probably doesn't work in Windows.

**Comment by addshore** [comment]
xD

**Comment by addshore** [comment]
You make me want to clone this repo again now...

**Pull request merged**
