### PR TITLE
Create a Github Actions workflow for Linux, macOS and Windows

### PR DESCRIPTION
**Pull request by phuzion**
This PR adds a GitHub Actions workflow, written based on the existing Travis-CI and AppVeyor build pipelines.

At this time, no changes have been made to the actual scripts used in the build process, so AppVeyor and Travis-CI will continue to work as they have for the time being.

As currently configured, CI is only run when commits are made to the repository. However, it is a simple process to include PRs, which may be something we want.

I've prepared a simple table showing the differences between the build environments for each operating system.

| Build System | Operating System | Specs |
| ------------- | ------------------ | ------ |
| AppVeyor (Windows) | Windows Server 2012 R2 | [2-core, 6GB RAM](https://www.appveyor.com/docs/build-environment/#build-vm-configurations) |
| Travis-CI (Linux) | Ubuntu 16.04 | [2-core, 7.5GB RAM](https://docs.travis-ci.com/user/reference/overview/#virtualisation-environment-vs-operating-system) |
| Travis-CI (Mac) | macOS 10.13 (High Sierra) | [2-core, 4GB RAM](https://docs.travis-ci.com/user/reference/overview/#virtualisation-environment-vs-operating-system)| 
| GitHub Actions (Windows) | Windows Server 2019 | [2-core, 7GB RAM](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources)
| GitHub Actions (Linux) | Ubuntu 18.04 | [2-core, 7GB RAM](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources)
| GitHub Actions (macOS) | macOS 10.15 (Catalina) | [3-core, 14GB RAM](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources) | 

As you can see, the operating systems are more modern, and the hardware specs are generally better.

Of note, macOS builds are running on a more modern OS, have an additional CPU core, and more than triple the RAM as compared to the Travis-CI infrastructure. Linux builds have slightly less ram than on Travis-CI, but complete in a comparable timeframe. [Linux builds will soon be automatically migrated to Ubuntu 20.04](https://github.com/actions/virtual-environments/issues/1816), with no action needed, as the ubuntu-latest tag will be redirected to 20.04.

Additionally, when macOS 11 (Big Sur) becomes available for everyone to use in GitHub Actions, there is a simple process to add that, which I will be happy to do. Currently, [GitHub Actions is not allowing new organizations to begin using the macOS 11 build environments yet](https://github.com/actions/virtual-environments/issues/2486), as they are seeing more demand for that buildsystem than they are ready for at the moment.

If there are any questions about this workflow, I am happy to answer here, or on IRC in #huggle on Freenode.

### CODE REVIEW

**Comment by phuzion** [comment]
As an additional note, you can see that these workflows do successfully build on all three OSes. [Here are the builds for the gha branch on my fork.](https://github.com/phuzion/huggle3-qt-lx/actions?query=branch%3Agha)

**Comment by benapetr** [comment]
ok one question - in past we used combination of different Qt version and OS to ensure it builds everywhere - eg. Qt4 on Linux and Qt5 on MacOS. Is this also covering Qt4? I am not even sure if Qt4 is still really supported on most platforms though, given that Qt6 is out.

**Comment by phuzion** [comment]
As written, this does not cover Qt4. I simply copied the behavior from Travis-CI and AppVeyor, reusing as much of the infrastructure as possible. We did not have Qt4 builds on either of the previous CI systems.

The action that I use to install Qt does not appear to support Qt4, so as written, we cannot use this workflow to test Qt4. I suspect that there are very few people who use Huggle that require the use of Qt4. If I am wrong about that, I'm happy to see if there are other ways to install older versions of Qt, and try that.

With a little bit of work, it should be relatively simple to set up a matrix that builds the software with various versions of Qt against various OSes (and even various versions of Visual Studio in the case of Windows, if we want that). For example, we could test Qt 5.12.10, 5.15.3, and 6.0 on Windows Server 2016, 2019, macOS 10.13, 10.14, 10.15 and Ubuntu 16.04, 18.04, and 20.04. I've already written most of the file to be version-independent, preferring to use variables wherever possible. I should be able to have this ready for a merge in the next few days.

Additionally, I am slowly working on automating the packaging process, which would automatically upload the completed DMGs or installers as [Artifacts](https://docs.github.com/en/actions/guides/storing-workflow-data-as-artifacts).

**Comment by phuzion** [comment]
I did a little more research, and have since found that GitHub Actions [only provides macOS 10.15](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources) currently, with macOS 11 (Big Sur) to come at a later time. 10.14 and 10.13 are not available.

Other than that, I am [getting very close](https://github.com/phuzion/huggle3-qt-lx/actions/runs/656520850) to having Huggle compiling on multiple versions of Ubuntu, Windows and macOS, with multiple versions of Qt each. It would also be trivial to set up Qt6 once we begin adding support for compiling on it. Currently, the matrix I have written compiles Huggle on Ubuntu 16.04, 18.04 and 20.04, as well as macOS 10.15, and Windows Server 2016 and 2019, and compiles with Qt 5.12.10 and 5.15.2. Additional Qt versions take all of a minute to add.

macOS builds appear to be failing for a completely unrelated transient reason (appears that Homebrew is struggling with a recently updated aws-sam-cli package), but I am confident once that issue is resolved, all builds should work again.

**Comment by phuzion** [comment]
[Happy to confirm that the macOS errors I was seeing were transient issues as I suspected.](https://github.com/phuzion/huggle3-qt-lx/actions/runs/656555581)

I'll give this a once-over and submit a new PR with the additional matrix of Qt versions and OSes momentarily.

**Pull request merged**
